/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import React from "react";

import Head from "next/head";
import HeroTop from "../components/HeroTop";
import ProjectText from "../components/ProjectText";
import Footer from "../components/Footer";
import ProjectFooter from "../components/ProjectFooter";

const AttendX = () => {
	const project = {
		name: "AttendX",
		id: 2,
		text: "Attendance Management System",
		image: "AttendX Web.png",
	};

	return (
		<>
			<Head>
				<title> AttendX </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='overflow-hidden md:pb-[24px] pb-[60px] '>
				{/* <hr className='w-screen h-[1px] md:h-[1.5px] bg-[#D7D7D7] mt-[34px] ' /> */}
				<div className='md:mx-[80px] mx-[16px] mt-[34px]  '>
					<div className=' flex flex-col gap-[48px] md:mb-[14px]  md:gap-[60px]   '>
						<HeroTop />
						<div className='md:mx-[60px]   '>
							<div className='flex flex-col  items-start justify-between '>
								<div className='flex flex-col space-y-[24px] mb-[16px]  border-transparent border-b-[#D7D7D7] border-[1.5px] pb-[16px] md:pb-[24px] w-full'>
									<h1 className='text-black text-[38px] md:text-[46px] leading-[46px] md:leading-[54px] tracking-[-2px] libre-reg '>
										{" "}
										{project.name}{" "}
									</h1>
								</div>

								<div className='flex flex-col space-y-[4px] '>
									<div className='flex space-x-2 items-center'>
										<h1 className=' text-[16px] leading-[24px] tracking-[-0.01px] md:text-[18px] text-[#212121] md:leading-[24px] md:tracking-[-0.1px] neue-md  '>
											Role:
										</h1>
										<p className='text-[#212121] text-[16px] leading-[24px]  neue-reg md:text-[16px] md:leading-[24px] md:tracking-[-0.1px] neue-reg  '>
											{" "}
											UI Designer{" "}
										</p>
									</div>
									<div className='flex space-x-2 items-center'>
										<h1 className=' text-[16px] leading-[24px] tracking-[-0.01px] md:text-[18px] text-[#212121] md:leading-[24px] md:tracking-[-0.1px] neue-md  '>
											Deliverables:
										</h1>
										<p className='text-[#212121] text-[16px] leading-[24px]  neue-reg md:text-[16px] md:leading-[24px] md:tracking-[-0.1px] neue-reg  '>
											{" "}
											Dashboard Design{" "}
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className='md:mx-[60px] flex flex-col space-y-[40px] md:space-y-[48px] '>
						<div className='   bg-[#D9D9D9] rounded-[2px]  my-[20px]  '>
							<img src='/AttendX Web.png' alt='dd' className='w-full' />
						</div>

						<div className='  flex flex-col space-y-[16px] md:space-y-[32px] '>
							<div className='flex flex-col gap-[8px] md:hidden '>
								<ProjectText
									text='According to the National Universities Commission in Nigeria, students must meet up to 75% lecture attendance to qualify for that course’s examination. According to their analysis, students who attend class regularly can improve their academic performance.
                           '
								/>

								<ProjectText
									text=' The general method used by some tertiary institutions during physical classes involves writing attendance on paper.
                                    In as much as this method is a means to an end, it can be easily manipulated by students and time consuming for lecturers to ensure that the attendance is free from such manipulation after each class.'
								/>

								<ProjectText
									text='
                            This system was developed by my course mate for his final year project, and I collaborated as a designer. The timeline was very short so we had to work at a fast pace.'
								/>
							</div>

							<div className='hidden md:block'>
								<ProjectText
									heading='Introduction'
									text='According to the National Universities Commission in Nigeria, students must meet up to 75% lecture attendance to qualify for that course’s examination. According to their analysis, students who attend class regularly can improve their academic performance. The general method used by some tertiary institutions during physical classes involves writing attendance on paper.
                            In as much as this method is a means to an end, it can be easily manipulated by students and time consuming for lecturers to ensure that the attendance is free from such manipulation after each class.
                            This system was developed by my course mate for his final year project, and I collaborated as a designer. The timeline was very short so we had to work at a fast pace.'
								/>
							</div>
							<a
                            href="https://project-nine-silk.vercel.app/"
                            target="_blank"
                            className='bg-gradient !md:p-0 !md:py-[10px] !md:px-[20px] tracking-[-0.01px] md:tracking-normal   w-[160px] h-[52px] flex items-center justify-center !px-[16px]  md:w-[160px] text-center cursor-pointer '>
								View Dashboard
							</a>
						</div>

						<div className=''>
							<ProjectText
								heading='The Goal'
								text='The goal of the project was to develop a student attendance system that uses QR code technology to improve attendance management.'
							/>
						</div>

						<div className='flex flex-col space-y-[8px] md:space-y-[16px]'>
							<ProjectText
								heading='Getting Started'
								text='I started by analyzing the system architecture and activity diagram, to get a visual interpretation of the flow which provided information on the type of users i was to design for. The design caters for two users:'
							/>

							<div>
								<ProjectText
									text='1. The lecturer whose role was to generate the QR code, and
                                keep track of attendance'
								/>
								<ProjectText
									text='	2. The student whose role was to scan the QR code generated to
                                validate attendance.'
								/>
							</div>

							<ProjectText text='Next, I gathered mood boards on data representation, color and layout. Afterward I moved to sketching out ideas. Having a lot of physical contact with the project’s owner helped a lot and we were able to move faster by sticking to sketching and making iterations on paper first before proceeding to designing the User Interface.' />
						</div>

						<div className=' flex flex-col space-y-[32px] '>
							<ProjectText
								heading='The Solution'
								text='Please refer to the video below for a visual demonstration of how the system works.'
							/>

							<div>
								<div className=' bg-[#D9D9D9] rounded-[2px]  w-full video-container   '>
									<video src='/ATTENDX.mp4' controls type='video/mp4'></video>
								</div>
								<h1 className='neue-reg text-[#646464] neue-md mt-[16px] '>
									Scanning the QR-Code to mark attendance
								</h1>
							</div>
						</div>

						<div>
							<h1 className='text-[#212121] neue-md md:leading-[32px] md:text-[24px] mb-[24px] '>
								Lecturer's Dashboard Designs
							</h1>
							<div className='bg-[#F9F9F9] rounded-[4px] md:py-[64px] md:px-[81px] '>
								<img
									src="/Lecturer's Dashboard AttendX web.png"
									alt="Lecturer's Dashboard AttendX web"
									className='w-full hidden md:block '
								/>
								<img
									src="/Lecturer's Dashboard Design.png"
									alt="Lecturer's Dashboard Design"
									className='w-full block md:hidden '
								/>
							</div>
						</div>

						<div>
							<h1 className='text-[#212121] neue-md md:leading-[32px] md:text-[24px] mb-[24px]  '>
								Student's Dashboard Designs
							</h1>
							<div className='bg-[#F9F9F9] rounded-[4px] md:py-[64px] md:px-[81px] '>
								<img
									src='/Student dashboard AttendX web.png'
									className='w-full hidden md:block '
								/>

								<img
									src="/Student's Dashboard Design.png"
									className='w-full md:hidden'
								/>
							</div>
						</div>

						<div>
							<h1 className='text-[#212121] neue-md md:leading-[32px] md:text-[24px] mb-[24px]  '>
								Mobile Responsiveness
							</h1>
							<div className='bg-[#F9F9F9] rounded-[4px] md:py-[64px] md:px-[81px] '>
								<img
									src='/Mobile responsiveness AttendX Web.png'
									className='w-full hidden md:block '
								/>

								<img
									src='/Mobile responsiveness.png'
									className='w-full  md:hidden '
								/>
							</div>
						</div>

						<div className='!mt-[64px]'>
							<ProjectFooter prev='/DigipassSimple' next='EzomonGlory' />
						</div>
					</div>
				</div>

				<Footer />
			</div>
		</>
	);
};

export default AttendX;
