/* eslint-disable react/no-unescaped-entities */
import React from "react";

import Head from "next/head";
import HeroTop from "../components/HeroTop";
import ProjectText from "../components/ProjectText";
import Footer from "../components/Footer";
import ProjectFooter from "../components/ProjectFooter";

const DigipassFull = () => {
	const project = {
		name: "Digipass",
		id: 2,
		text: "Attendance Management System",
		image: "AttendX Web.png",
	};

	return (
		<>
			<Head>
				<title> DigiPass </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='overflow-hidden md:pb-[40px] pb-[24px] '>
				{/* <hr className='w-screen h-[1px] md:h-[1.5px] bg-[#D7D7D7] mt-[34px] ' /> */}
				<div className='md:mx-[80px] mx-[16px] mt-[34px]   '>
					<div className=' flex flex-col gap-[24px] md:mb-[14px]  md:gap-[60px]   '>
						<HeroTop />
						<div className='md:mx-[60px] mx-[16px]  '>
							<div className='flex flex-col  items-start justify-between '>
								<div className='flex flex-col space-y-[24px] mb-[16px]  border-transparent border-b-[#D7D7D7] border-[1.5px] pb-[24px] w-full'>
									<h1 className='text-black text-[30px] md:text-[46px] leading-[32px] md:leading-[54px] md:tracking-[-2.76px] libre-reg '>
										{" "}
										{project.name}{" "}
									</h1>
								</div>

								{/* <div className='border-[1px] border-[#e22] rounded-[24px] md:px-[20px] md:py-[10px] px-[24px] py-[10px] md:text-[18px] neue-md md:leading-[28px] md:tracking-[-0.54px] text-[#e22]  space-x-[8px] items-center hidden md:flex w-max  '>
									<p>Vist Site</p>
									{redArrWeb}
									{redArrMobile}
								</div> */}
								<div className='flex flex-col space-y-[4px] '>
									<div className='flex space-x-2 items-center'>
										<h1 className=' text-[14px] leading-[20px] tracking-[-0.6px] md:text-[18px] text-black md:leading-[28px] md:tracking-[-1.08px] libre-reg  '>
											Role:
										</h1>
										<p className='text-[#787878] text-[12px] leading-[22px]  neue-reg md:text-[16px] md:leading-[24px] md:tracking-[-0.16px]  '>
											{" "}
											UI Designer, Researcher{" "}
										</p>
									</div>
									<div className='flex space-x-2 items-center'>
										<h1 className=' text-[14px] leading-[20px] tracking-[-0.6px] md:text-[18px] text-black md:leading-[28px] md:tracking-[-1.08px] libre-reg  '>
											Deliverables:
										</h1>
										<p className='text-[#787878] text-[12px] leading-[22px]  neue-reg md:text-[16px] md:leading-[24px] md:tracking-[-0.16px]  '>
											{" "}
											Dashboard Design, App Design{" "}
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className='md:mx-[60px] flex flex-col space-y-[48px] '>
						<div className='   rounded-[2px]  my-[20px]  '>
							<img src='/DigiPass Web.png' alt='dd' className='w-full' />
						</div>

						<div className='  flex flex-col  '>
							<ProjectText
								heading='Overview'
								text='As a final year university student majoring in Computer Science, I had to work on something significant for my final year project as part of the academic requirements. I had to analyze the myriad of existing systems/operations in the department and chose to improve the methods in which students are verified before they are granted access into the examination hall.'
							/>
						</div>

						<div className=''>
							<ProjectText
								heading='The Existing System'
								text='In previous academic sessions, the Department utilized paper-based examination passes as the primary method for verifying students before admitting them into the examination hall. These examination passes were provided to students after ensuring they paid their tuition fees and registered for the courses they offered during the session. The passes became a prerequisite for entering the exam hall. These examination passes contain vital information about the students, such as their full name, academic level and the courses they registered for during that semester or session. I will be unable to upload an image of the exam pass used due to confidential reasons.'
							/>
						</div>

						<div className='flex flex-col space-y-[16px]'>
							<ProjectText
								heading='Research'
								text='Being fortunate to have access to past examination passes used in previous academic sessions allowed me to carefully study and analyze them. After studying the examination passes and drafting my observations, I conducted interviews with departmental lecturers to clarify and verify the information gathered through my observation. I was able to gather valuable insights regarding the process. While the confidentiality of the interview details is essential, several key findings emerged:'
							/>
							<ol>
								<li className='text-[#646464]'>
									{" "}
									1. The examination pass serves as an additional means of
									student identification during exams, and its useis limited to
									my department alone.
								</li>
								<li className='text-[#646464]'>
									2. The method used to verify the validity of the examination
									pass is by confirming if the picture on the pass matches the
									individual presenting it and if it carries the Head of
									department signature.
								</li>
							</ol>

							<ProjectText text='As a subject of the method, I was able to compare my experiences and analysis with the results from the interviews and realized that there is an absence of an efficient system that grants students access to the examination halls. Even with the current measures applied, issues of impersonation continue to arise.' />
						</div>

						<div className=''>
							<ProjectText
								heading='The Goal'
								text="Based on the insights I gathered, I formulated the project's goal, which is to enhance the methods of student identification during examinations within my department."
							/>
						</div>

						<div className='flex flex-col space-y-[16px]'>
							<ProjectText
								heading='Approaching The Problem'
								text='During the brainstorming phase, I collaborated with a peer who offered valuable insight on approaching the problem. He suggested leveraging on Near Field Communication (NFC) technology, highlighting its successful applications in various countries as a secure means of payment and its current implementation within the transportation sector in Nigeria (Lagos State specifically). While other ideas emerged during our brainstorming session, I had to consider certain factors like implementation time and cost.'
							/>

							<ProjectText text='The proposed system was named "Digipass." This name is a fusion of "Digital" and "Pass," signifying its role in revolutionizing the exam screening process. Digipass harnesses the potentials of Near Field Communication (NFC) Technology to enhance this process.' />

							<ProjectText text='Digipass introduces a range of features to efficiently verify student details and manage exam attendance. With the utilization of NFC Cards and NFC-enabled smartphones, students can be seamlessly clocked in and out of examinations hall to ascertain their attendance, significantly improving the existing methods employed within the department.' />

							<div>
								<img
									src='/Activity duagram Digipass Web.png'
									className='w-full'
								/>
							</div>

							<ProjectText text='I collaborated with an app developer and a frontend engineer to create the system. We worked together to define the system architecture, which served as a foundation for planning the user experience and as a blueprint for the technical implementation by the developers.' />
						</div>

						<ProjectText
							heading='Testing and Iterations'
							text='I had limited time to design and ensure the implementation of my project before the defense. We had to work concurrently, testing alongside production, with a primary focus on quickly verifying that critical functionalities were operating as expected and identifying any potential setbacks. Simultaneously, I observed and collected feedback from real users as they interacted with the app during this period.'
						/>

						<div className=' flex flex-col space-y-[16px] '>
							<div className="flex flex-col space-y-[24px]" >
								<ProjectText
									heading='Registering Students'
									text='Before students can be verified, their details must have been registered on the dashboard to link the NFC card with their information before they are assigned an NFC card. Part of the registration process on the dashboard includes entering the NFC card number assigned to the NFC card. Please refer to the video below for a visual demonstration.'
								/>

								<div className=' bg-[#D9D9D9] rounded-[2px] h-[400px]'></div>
							</div>
							<h1 className='neue-reg text-[#646464] tracking-[-0.1px] '>
								Obtaining the NFC card serial number from the live mobile
								authenticator.
							</h1>

							<div className=' bg-[#D9D9D9] rounded-[2px] h-[400px] !mt-[24px]  '></div>
							<h1 className='neue-reg text-[#646464] tracking-[-0.1px] '>
								Registering the NFC Card on the live dashboard.
							</h1>
						</div>

						<div className=' flex flex-col space-y-[32px] '>
							<ProjectText
								heading='Verifying Students'
								text="The card displays the same information as the traditional exam pass used by my department. The key distinction lies in its automated and highly secure approach to verifying student identities before granting them access to the examination hall.
                                If the student's identity is confirmed, their photograph matches their appearance, and the course exam they intend to write aligns with their registered courses, they can then be clocked in for that course. Please refer to the video below for a visual demonstration"
							/>

							<div className=' bg-[#D9D9D9] rounded-[2px] h-[400px]   '></div>
							<h1 className='neue-reg text-[#212121]'>
								Scanning the NFC Card to verify the student’s detail
							</h1>
						</div>

						<div className=' flex flex-col space-y-[32px] '>
							<ProjectText
								heading='Managing Exam Attendance'
								text='The system records students as they clock in to take an exam, and this information is reflected on the dashboard.
                                To enhance the security of the platform, once a student has clocked in for an exam, they cannot clock in for another exam unless they have previously clocked out from the previous exam. Please refer to the video below for further clarification.'
							/>

							<div className=' bg-[#D9D9D9] rounded-[2px] h-[400px]   '></div>
							<h1 className='neue-reg text-[#212121]'>
								Clocking in a student that has already been clocked in
							</h1>
						</div>

						<div>
							<h1 className='text-[#212121] neue-md md:leading-[32px] md:text-[24px] mb-[24px] '>
								Application Design
							</h1>
							<div className='bg-[#F9F9F9] rounded-[4px] md:py-[64px] md:px-[81px] '>
								<img
									src='/Application Design Digipass Web.png'
									alt='Application Design Digipass Web'
									className='w-full'
								/>
							</div>
						</div>

						<div>
							<h1 className='text-[#212121] neue-md md:leading-[32px] md:text-[24px] mb-[24px]  '>
								Dashboard Design
							</h1>
							<div className='bg-[#F9F9F9] rounded-[4px] md:py-[64px] md:px-[81px] '>
								<img
									src='/Dashboard design Digipass Web.png'
									className='w-full'
								/>
							</div>
						</div>

						<div className='flex flex-col space-y-[16px]'>
							<ProjectText
								heading='Enhancing Student Identification on Campus: 
                            Insights Uncovered During My Project'
								text="Instead of the conventional student identity card, NFC cards have the potential to serve multiple purposes, including acting as both an exam pass and a student identification card. Since these cards are plain white, it's possible to print a sticker containing the student's details on the card. This way, the card becomes a versatile tool for both exam verification and identification purposes."
							/>

							<ProjectText text="Additionally, the mobile authenticator can be integrated with a campus portal to retrieve students' details directly. This integration ensures that the card's information is always up-to-date, reflecting any changes made by students through their portal accounts. As part of my project, we developed a basic dashboard to demonstrate how this system is intended to function." />
						</div>
						<div>
							<ProjectFooter />
						</div>
					</div>
				</div>

				<Footer />
			</div>
		</>
	);
};

export default DigipassFull;
