import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Work from "../components/Work";
import About from "../components/About";
import Footer from "../components/Footer";
import FotterBottom from "../components/FotterBottom";

export default function Home() {
	return (
		<div>
			<Head>
				<title>David Otu</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='md:py-[40px] md:px-[64px] py-[32px] px-[16px]'>
				<Hero />
				<Work />
				<About />
			</main>
			<Footer />
		</div>
	);
}
